version: '3.8'

services:
  frontend:
    build:
      context: ./frontend   
    ports:
      - "8080:80"

  api:
    build:
      context: ./backend    
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
