version: '3.8'
services:
  api:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    ports:
      - "8080:80"
