apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ganraj99215/portfolio-backend:latest
        env:
        - { name: PORT, value: "5000" }
        - { name: HOST, value: "0.0.0.0" }
        ports: [{ containerPort: 5000 }]
        resources:
          requests: { cpu: "50m", memory: "128Mi" }
          limits:   { cpu: "300m", memory: "256Mi" }
