apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: portfolio  # ✅ IMPORTANT: Ensure namespace is specified
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ganraj99215/portfolio-backend:v1  # ✅ USE YOUR CORRECT IMAGE NAME HERE
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: portfolio  # ✅ Must match deployment and ingress namespace
spec:
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP

