apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: portfolio
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 3000        # Port exposed inside cluster
      targetPort: 3000  # Port inside the container
  type: ClusterIP
