apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ganraj99215/backend:latest
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /reviews
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /reviews
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
