apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: cicd-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ganraj99215/backend:latest
          ports:
            - containerPort: 5000
