apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cicd-ingress
  namespace: portfolio
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: cicd.devopsbyganraj.cloud
      http:
        paths:
          # Frontend
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80

          # Backend API
          - path: /api/?(.*)
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3000

          # Prometheus
          - path: /prometheus/?(.*)
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: 9090

          # Grafana
          - path: /grafana/?(.*)
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000

          # SonarQube
          - path: /sonarqube/?(.*)
            pathType: Prefix
            backend:
              service:
                name: sonarqube
                port:
                  number: 9000

          # Zabbix
          - path: /zabbix/?(.*)
            pathType: Prefix
            backend:
              service:
                name: zabbix-server
                port:
                  number: 80
