apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cicd-frontend-ingress
  namespace: cicd
spec:
  ingressClassName: nginx
  rules:
    - host: cicd.devopsbyganraj.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
