apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-ingress
  namespace: cicd-portfolio
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: cicd-portfolio-backend-rewrite@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: cicd.devopsbyganraj.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: /backend
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 5000
---
# Middleware for backend path rewrite
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: backend-rewrite
  namespace: cicd-portfolio
spec:
  replacePathRegex:
    regex: ^/backend/(.*)
    replacement: /$1
