apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cicd-backend-ingress
  namespace: cicd
spec:
  rules:
  - host: cicd.devopsbyganraj.cloud
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 5000

