apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cicd-ingress
  namespace: portfolio
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: cicd.devopsbyganraj.cloud
      http:
        paths:
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  number: 80

          - path: /api()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend-service   # ✅ Must match backend svc name
                port:
                  number: 3000

          - path: /prometheus
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: 9090
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
          - path: /sonarqube
            pathType: Prefix
            backend:
              service:
                name: sonarqube
                port:
                  number: 9000
          - path: /zabbix
            pathType: Prefix
            backend:
              service:
                name: zabbix-server
                port:
                  number: 80
